language: java

matrix:
  include:
  - jdk: openjdk8
  - jdk: oraclejdk8

install: mvn install clirr:check -Dgpg.skip

after_success:
  - mvn -DrepoToken=${coveralls_token} clean test jacoco:report coveralls:report --projects=logwebconfig
cache:
    directories:
    - $HOME/.m2
